//! Raw FFI bindings to the vendored `lib60870-C` library
//! (https://github.com/mz-automation/lib60870), generated by `bindgen` in
//! `build.rs`.
//!
//! This module intentionally stays a thin, unsafe, 1:1 mirror of the C API.
//! Safe wrappers (RAII types, error mapping, `Send`/`Sync` bounds, etc.)
//! belong in the parent `iec_60870_dev` module, not here.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
